# Generated by Django 5.2.4 on 2025-08-20 15:47

import content.utils
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary'), ('Animation', 'Animation')], max_length=50)),
                ('original_video', models.FileField(upload_to=content.utils.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv']), content.utils.validate_video_size])),
                ('thumbnail_url', models.ImageField(upload_to=content.utils.thumbnail_upload_path)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hls_480p_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hls_720p_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hls_1080p_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='unique_title_case_insensitive')],
            },
        ),
    ]
